namespace CoreAppUWP.WinRT
{
    [default_interface]
    runtimeclass HookRegistry
    {
        HookRegistry();

        Boolean IsHooked { get; set; };

        void StartHook();
        void EndHook();
    }
}
