namespace CoreAppUWP.WinRT
{
    enum WindowingModel
    {
        None = 0,
        Universal = 1,
        ClassicDesktop = 2,
        ClassicPhone = 3
    };

    [default_interface]
    runtimeclass HookWindowingModel : Windows.Foundation.IClosable
    {
        HookWindowingModel();

        static WindowingModel WindowingModel { get; set; };

        Boolean IsHooked { get; set; };

        void StartHook();
        void EndHook();
    }
}
