namespace CoreAppUWP.WinRT
{
    [default_interface]
    runtimeclass HookRegistry : Windows.Foundation.IClosable
    {
        HookRegistry();

        Boolean IsHooked { get; set; };

        void StartHook();
        void EndHook();
    }
}
