<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Native-Platform>$(Platform)</Native-Platform>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.Gaming.XboxGameBar" Version="7.3.2506120" GeneratePathProperty="true" />
  </ItemGroup>

  <ItemGroup>
    <CsWinRTInputs Include="$(PkgMicrosoft_Gaming_XboxGameBar)\**\*.winmd" />
  </ItemGroup>

  <ItemGroup>
    <ReferenceCopyLocalPaths Include="$(PkgMicrosoft_Gaming_XboxGameBar)\lib\uap10.0\Microsoft.Gaming.XboxGameBar.winmd" />
    <ReferenceCopyLocalPaths Include="$(PkgMicrosoft_Gaming_XboxGameBar)\runtimes\win10-$(Native-Platform)\native\Microsoft.Gaming.XboxGameBar.dll" />
    <ReferenceCopyLocalPaths Include="$(PkgMicrosoft_Gaming_XboxGameBar)\runtimes\win10-$(Native-Platform)\native\Microsoft.Gaming.XboxGameBar.pri" />
    <ReferenceCopyLocalPaths Include="$(PkgMicrosoft_Gaming_XboxGameBar)\private\Microsoft.Gaming.XboxGameBar.Private.winmd" />
  </ItemGroup>

  <Import Project="$(PkgMicrosoft_Gaming_XboxGameBar)\build\Microsoft.Gaming.XboxGameBar.targets"/>
  <Import Project="$(PkgMicrosoft_Gaming_XboxGameBar)\build\Microsoft.Gaming.XboxGameBar.props"/>
</Project>