<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ApplicationEntryPoint>CoreAppUWP.App</ApplicationEntryPoint>
    <ApplicationIcon>favicon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <DefaultLanguage>en-US</DefaultLanguage>
    <DefineConstants>$(DefineConstants);DISABLE_XAML_GENERATED_MAIN</DefineConstants>
    <EnableMsixTooling>True</EnableMsixTooling>
    <OutputType>WinExe</OutputType>
    <Platforms>x86;x64;ARM64</Platforms>
    <PublishAot>True</PublishAot>
    <PublishProfile>win10-$(Platform).pubxml</PublishProfile>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <UseUwp>True</UseUwp>
    <VersionPrefix>0.0.1</VersionPrefix>
  </PropertyGroup>

  <PropertyGroup>
    <MicrosoftWindowsSDKBuildToolsMSIXPackageVersion>1.7.20250528.2</MicrosoftWindowsSDKBuildToolsMSIXPackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Labs.Uwp.Controls.MarkdownTextBlock" Version="0.1.250703-build.2173" />
    <PackageReference Include="CommunityToolkit.Uwp.Controls.Primitives" Version="8.2.250402" />
    <PackageReference Include="CommunityToolkit.Uwp.Controls.SettingsControls" Version="8.2.250402" />
    <PackageReference Include="Detours.Win32Metadata" Version="4.0.1.18" />
    <PackageReference Include="Karambolo.Extensions.Logging.File" Version="3.6.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.6" />
    <PackageReference Include="Microsoft.Toolkit.Uwp.Notifications" Version="7.1.3" />
    <PackageReference Include="Microsoft.UI.Xaml" Version="2.8.7" />
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.183" PrivateAssets="all">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.WindowsAppSDK.Base" Version="1.8.250509001-experimental" />
    <PackageReference Include="Microsoft.WindowsAppSDK.InteractiveExperiences" Version="1.8.250626001-experimental" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="AppPackages\**" />
    <None Remove="BundleArtifacts\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="favicon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\About\About.en-US.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
