name: build and package

on:
  push:
    branches: [wuxc]
  pull_request:
    branches: [wuxc]
    paths:
      - '.github/workflows/build-and-package.yml'
      - 'CoreAppUWP**'
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x' # The .NET SDK version to use

jobs:
  build-and-test:

    name: build-and-package
    runs-on: windows-latest

    env:
      Solution_Name: CoreAppUWP.Package/CoreAppUWP.Package.wapproj
      Project_Directory: CoreAppUWP

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core App workload
    - name: Install .NET Core App
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration /p:PublishReadyToRun=true
      env:
        Configuration: Release

    # Create the app package by building and packaging the Windows Application Packaging project
    - name: Create the app package
      run: msbuild $env:Solution_Name `
        /p:AppxBundlePlatforms="$env:Appx_Bundle_Platforms" `
        /p:Configuration=$env:Configuration `
        /p:UapAppxPackageBuildMode=$env:Appx_Package_Build_Mode `
        /p:AppxBundle=$env:Appx_Bundle `
        /p:AppxPackageDir="$env:Appx_Package_Dir" `
        /p:AppxPackageSigningEnabled=false
      env:
        Appx_Bundle: Always
        Appx_Bundle_Platforms: x86|x64|ARM64
        Appx_Package_Build_Mode: SideloadOnly
        Appx_Package_Dir: AppxPackages\
        Configuration: Release

    # Upload the MSIX package: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MSIX Package
        path: CoreAppUWP.Package/AppxPackages/**
